### ISSUE TITLE
https://safenetforum.org/ broken (at least using Firefox)

### ISSUE THREAD

**Issue by jonassmedegaard** [maidsafe/maidsafe.github.io#132]
When I go to <https://safenetforum.org/> in Firefox, I am presented an error message (in danish - talks about error in transmission of data).

I guess https://safenetforum.org/ has moved to <https://forum.safedev.org/> and some setup (related to certificates?) still points to the old site, where instead the old site should be kept alive but serve a 301 or 302 redirect?

**Comment by lionel1704** [comment]
Hey @jonassmedegaard! I am using firefox too and the https://safenetforum.org link is working fine.
Could you please try hard-refreshing the page ( Ctrl + Shift + R ) and if the issue still persists maybe share a screenshot of your error page. Thank you.

**Comment by jonassmedegaard** [comment]
Already tried hard-refreshing - no luck.

Here's the content of the error message:

Fejlbehæftet indhold

Siden http://safenetforum.org/ kan ikke vises, da der er fundet en fejl i transmissionen af data.

Siden, du forsøger at se, kan ikke vises, da der er fundet en fejl i overførslen af data.

    Kontakt ejerne af webstedet omkring dette problem.

**Comment by jonassmedegaard** [comment]
Here's the error I get in the debugging console when pressing F12:

> Kunne ikke indlæse 'https://safenetforum.org/'. En ServiceWorker videresendte et promise til FetchEvent.respondWith(), som afviste med 'Error: TypeError: NetworkError when attempting to fetch resource.'.

**Comment by jonassmedegaard** [comment]
hostname resolves correctly, and fetching the same resource with wget succeeds

**Comment by jonassmedegaard** [comment]
Hm. Was apparently some corruption of my local caching in Firefox after all - purging all cache today made it succeed (didn't try that earlier because I had same issue yesterday and then it tried restarting the browser which didn't help).

Sorry for the noise!
