### ISSUE TITLE
Highlight changes to core for new arrivals

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/maidsafe.github.io#40]
While things are in flux and until this page is updated it would help new potential devs to know that:
- the libraries are being re-organised
- all except ??? are being rewritten in Rust to improve security, reduce codebase, improve reliability and productivity

I suggest adding a short "red" paragraph to this effect at the top. Otherwise it's confusing and annoying to start with the picture from this page and find things different when delving into github and elsewhere.

**Comment by dirvine** [comment]
Good point, we should do something about that.

**Comment by NickLambert** [comment]
I've raised a Jira task to get this done. Thanks for the heads up.
